name: Laragram tests
on:
  pull_request:
    branches: [master, development]
jobs:
  build-and-run-tests:
    runs-on: ubuntu-16.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: forge
          MYSQL_DATABASE: forge
          DB_HOST: localhost
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Dependencies (PHP vendors)
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist && npm ci

    - name: Generate key
      run: php artisan key:generate

    - name: Build site
      run: npm run dev

    - name: Execute unit tests via PHPUnit
      run: vendor/bin/phpunit

    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        install: false
        start: npm start
        wait-on: http://localhost:8000
        config-file: cypress.json
        spec: cypress/integration/laragram/laragram.spec.js
      env:
        CYPRESS_baseUrl: http://localhost:8000